# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tibet Unlocked
email: tibetaction21@gmail.com
description: "write something for descriptions"
subtitle: "And for subtitle"
lang: en-us
author: Tibet Action
copyright: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "tibetunlocked.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  

permalink: /:year/:title.html

#Timezone


#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']